version: '3'
services:
  vote:
    image: voting-app
    container_name: vote
    ports:
      - '5000:80'
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres:9.4
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  worker:
    image: worker-app
    container_name: worker
    depends_on:
      - redis
      - db
  result:
    image: result-app
    container_name: result
    ports:
      - 5001:80
    depends_on:
      - db
